CC:=gcc

01num_endianness_convert: 01num_endianness_convert.c
	-$(CC) -o $@ $<
	-./$@
	-rm -f $@

02inet_endian_convert: 02inet_endian_convert.c
	-$(CC) -o $@ $<
	-./$@
	-rm -f $@

03single_connect_server: 03single_connect_server.c
	-$(CC) -o $@ $<
#	-./$@
#	-rm -f $@

04single_connect_client: 04single_connect_client.c
	-$(CC) -o $@ $<
#	-./$@
#	-rm -f $@